name: Publish Image
on:
  schedule:
    - cron: '22 4 * * *'
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
    paths:
      - 'Dockerfile'
      - '.github/workflows/ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'Dockerfile'
      - '.github/workflows/ci.yml'
jobs:
  build:
    name: 'OCI'
    uses: curium-rocks/flows/.github/workflows/oci-build-image.yml@main
    with:
      registry: ghcr.io/bryopsida
      image_name: tailscale